import { Document, Page, Text, View, Image, StyleSheet, pdf } from '@react-pdf/renderer';
import React from 'react';
import { Job } from '@/types';

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 10, color: '#1a1a1a' },
  header: { marginBottom: 20, borderBottomWidth: 2, borderBottomColor: '#1a56db', paddingBottom: 10 },
  title: { fontSize: 20, fontFamily: 'Helvetica-Bold', color: '#1a56db' },
  subtitle: { fontSize: 11, color: '#555', marginTop: 2 },
  section: { marginTop: 16, marginBottom: 8 },
  sectionTitle: { fontSize: 13, fontFamily: 'Helvetica-Bold', marginBottom: 6, color: '#1a56db' },
  vehicleRow: { flexDirection: 'row', marginBottom: 3 },
  label: { fontFamily: 'Helvetica-Bold', width: 100 },
  value: { flex: 1 },
  panelBlock: { marginBottom: 12, padding: 8, backgroundColor: '#f7f9fc', borderRadius: 4 },
  panelTitle: { fontFamily: 'Helvetica-Bold', marginBottom: 4 },
  photoGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 4, marginBottom: 8 },
  photo: { width: 120, height: 90, objectFit: 'cover', borderRadius: 3 },
  narrative: { lineHeight: 1.6, fontSize: 10 },
  footer: {
    position: 'absolute',
    bottom: 24,
    left: 40,
    right: 40,
    borderTopWidth: 1,
    borderTopColor: '#ccc',
    paddingTop: 6,
    fontSize: 8,
    color: '#888',
  },
});

interface ReportDocumentProps {
  job: Job;
}

function ReportDocument({ job }: ReportDocumentProps) {
  const { vehicle, damagedPanels, report, exteriorPhotos } = job;
  const narrative = report?.editedNarrative ?? report?.narrative ?? '';

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.title}>Tech-Assist Damage Report</Text>
          <Text style={styles.subtitle}>
            Generated {report?.generatedAt?.toDate?.().toLocaleDateString() ?? new Date().toLocaleDateString()}
          </Text>
        </View>

        {/* Vehicle Info */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Vehicle Information</Text>
          {[
            ['VIN', vehicle.vin],
            ['Year / Make / Model', `${vehicle.year} ${vehicle.make} ${vehicle.model}`],
            ['Body Style', vehicle.bodyStyle],
            ['Paint Code', vehicle.paintCode],
            ['Paint Stages', String(vehicle.paintStages)],
          ].map(([label, value]) => (
            <View style={styles.vehicleRow} key={label}>
              <Text style={styles.label}>{label}:</Text>
              <Text style={styles.value}>{value}</Text>
            </View>
          ))}
        </View>

        {/* Exterior Photos */}
        {Object.values(exteriorPhotos).some(Boolean) && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Exterior Overview Photos</Text>
            <View style={styles.photoGrid}>
              {Object.entries(exteriorPhotos)
                .filter(([, url]) => !!url)
                .map(([position, url]) => (
                  <Image key={position} src={url!} style={styles.photo} />
                ))}
            </View>
          </View>
        )}

        {/* Damaged Panels */}
        {damagedPanels.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Damage Assessment — Per Panel</Text>
            {damagedPanels.map((panel) => (
              <View style={styles.panelBlock} key={panel.panelId}>
                <Text style={styles.panelTitle}>{panel.panelId.replace(/_/g, ' ').toUpperCase()}</Text>
                {panel.photoUrl && <Image src={panel.photoUrl} style={{ width: 200, height: 150, marginBottom: 6, objectFit: 'cover' }} />}
                {[
                  ['Dent Depth', panel.assessment.dentDepth],
                  ['Dent Type', panel.assessment.dentType],
                  ['Body Lines', panel.assessment.bodyLines.join(', ') || 'None detected'],
                  ['Feather Edge Area', `${panel.assessment.featherEdgeArea} sq in`],
                  ['Blend Area', `${panel.assessment.blendArea} sq in`],
                  ['3-Stage Impact', panel.assessment.paintStageImpact ? 'Yes' : 'No'],
                ].map(([l, v]) => (
                  <View style={styles.vehicleRow} key={l}>
                    <Text style={styles.label}>{l}:</Text>
                    <Text style={styles.value}>{v}</Text>
                  </View>
                ))}
              </View>
            ))}
          </View>
        )}

        {/* Narrative */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Repair Justification</Text>
          <Text style={styles.narrative}>{narrative}</Text>
        </View>

        {/* Footer */}
        <Text style={styles.footer}>
          This report was generated by Tech-Assist using AI-assisted damage analysis. All assessments are based on
          I-CAR procedures and OEM guidelines. Final repair time authorization is subject to adjuster review.
        </Text>
      </Page>
    </Document>
  );
}

export async function exportPdf(job: Job): Promise<Blob> {
  return pdf(<ReportDocument job={job} />).toBlob();
}
